---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en-GB
useGitignore: true
dictionaries:
  - custom-misc
  - library-terms
  - people
  - maths-terms
  - acronyms
  - python
dictionaryDefinitions:
  - name: custom-misc
    path: ./.cspell/custom_misc.txt
    addWords: true
  - name: library-terms
    path: ./.cspell/library_terms.txt
    addWords: true
  - name: people
    path: ./.cspell/people.txt
    addWords: true
  - name: maths-terms
    path: ./.cspell/maths_terms.txt
    addWords: true
  - name: acronyms
    path: ./.cspell/acronyms.txt
    addWords: true
ignoreRegExpList:
  - /doi\s*=\s*\{[\w./-]+}/ # ignore DOIs in .bib files
