name: "Bug Report"
description: "Report a problem"
title: "[Bug]: "
labels: ["bug", "new"]
projects: ["gchq/16"]
body:
  - type: markdown
    attributes:
      value: |
        _Before reporting_: search [existing issues](https://github.com/gchq/Vanguard/issues) to see if an issue already exists for the bug you encountered.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "What's the problem?"
      description: "What are you doing? What happens? How is this different from expected?"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "How is the issue reproduced?"
      description: "List the steps to reproduce the behaviour"
      placeholder: |
        1. Run '...'
        1. See error...
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: "Python version"
      description: "What version of Python are you using?"
      placeholder: "3.10"
    validations:
      required: true
  - type: input
    id: vanguard-version
    attributes:
      label: "Package version"
      description: "What version of Vanguard are you using?"
      placeholder: "2.1.0"
    validations:
      required: true
  - type: textarea
    id: operating-system
    attributes:
      label: "Operating system"
      description: "What OS are you using? (Windows, Linux, or Mac, and version)"
      placeholder: "Ubuntu 23.04.2"
    validations:
      required: true
  - type: textarea
    id: other-packages
    attributes:
      label: "Other packages"
      description: "Are there any other packages in your environment not listed in the dependencies?"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output. This is automatically formatted as code, so no backticks are required.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/gchq/coreax/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
