name: Check for unlinked TODOs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  check-todos:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Clean installation
      run: |
        pip freeze --exclude-editable | xargs pip uninstall -y || pip freeze
    - name: Install Ruff
      run: pip install ruff
    - name: Check for unlinked TODOs
      run: ruff check --select=TD --ignore=TD002
