name: Build Documentation

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build documentation with latest dependencies
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          # TODO: Re-enable when going public
          # https://github.com/gchq/Vanguard/issues/257
          # cache: pip
          # cache-dependency-path: pyproject.toml
      - name: Upgrade pip and pipenv
        run: python -m pip install --upgrade pip pipenv
      - name: Install documentation dependencies
        run: pipenv run pip install -e .[doc]
      - name: Build documentation
        run: |
          pipenv run python -m sphinx -b html -aE docs/source docs/build
      - name: Check external links
        run: |
          pipenv run python -m sphinx -b linkcheck docs/source docs/build
  build-pinned:
    name: Build documentation with pinned package versions
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          # TODO: Re-enable when going public
          # https://github.com/gchq/Vanguard/issues/257
          # cache: pip
          # cache-dependency-path: requirements-docs.txt
      - name: Upgrade pip and pipenv
        run: python -m pip install --upgrade pip pipenv
      - name: Install documentation dependencies
        run: pipenv run pip install -r requirements-docs.txt --no-deps
      - name: Build documentation
        run: |
          pipenv run python -m sphinx -b html -aE docs/source docs/build
      - name: Check external links
        run: |
          pipenv run python -m sphinx -b linkcheck docs/source docs/build
      - name: Clean up pipenv's virtualenv
        run: pipenv --rm
        if: always()
