name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      # Set the Python version that `uv` will use for its virtual environment.
      UV_PYTHON: 3.13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          # Note that this is just the version of Python that we use to run `uv` with.
          # `uv` manages its own version of Python.
          # For speed, we use the same version for both, but in principle these could differ.
          python-version: 3.13
      - name: Set up uv cache directory location
        run: echo "UV_CACHE_DIR=${{ runner.temp }}/.uv-cache" >> $GITHUB_ENV
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}-${{ env.UV_PYTHON }}-doc
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}-${{ env.UV_PYTHON }}
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --extra doc --no-dev --locked
      - name: Debug - uv pip freeze
        run: uv pip freeze
      - name: Build documentation
        run: |
          uv run -m sphinx -b html --write-all --fresh-env --nitpicky --fail-on-warning --keep-going docs/source docs/build
      - name: Check external links
        run: |
          uv run -m sphinx -b linkcheck docs/source docs/build
      - name: Minimize UV cache
        run: uv cache prune --ci
        if: always()
