name: Pre-commit Checks

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "**"


jobs:
  pre_commit:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          # TODO: Re-enable when going public
          # https://github.com/gchq/Vanguard/issues/257
          # cache: pip
          # cache-dependency-path: setup.py
      - name: Set up uv cache directory location
        run: echo "UV_CACHE_DIR=${{ runner.temp }}/.uv-cache" >> $GITHUB_ENV
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-dev-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-dev-${{ hashFiles('pyproject.toml') }}
            uv-${{ runner.os }}-dev
            uv-${{ runner.os }}
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Clean installation
        run: |
          pip freeze --exclude-editable | xargs pip uninstall -y || pip freeze
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Remove fail_fast from Pre-commit config
        run: sed -e "/fail_fast/d" .pre-commit-config.yaml > /tmp/.pre-commit-config-ci.yaml
      - name: Run Pre-commit checks
        run: SKIP=no-commit-to-branch uv run pre-commit run --all-files --show-diff-on-failure --config /tmp/.pre-commit-config-ci.yaml
      - name: Minimize UV cache
        run: uv cache prune --ci
        if: always()
