name: Pre-commit Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  pre_commit:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Remove fail_fast from Pre-commit config
        run: sed -e "/fail_fast/d" .pre-commit-config.yaml > /tmp/.pre-commit-config-ci.yaml
      - name: Run Pre-commit checks
        run: SKIP=no-commit-to-branch pre-commit run --all-files --show-diff-on-failure --config /tmp/.pre-commit-config-ci.yaml
