name: Tests from requirements file

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "**"


jobs:
  tests:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        # TODO: Re-enable when going public
        # https://github.com/gchq/Vanguard/issues/257
        # cache: pip
        # cache-dependency-path: requirements.txt
    - name: Set up uv cache directory location
      run: echo "UV_CACHE_DIR=${{ runner.temp }}/.uv-cache" >> $GITHUB_ENV
    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: uv-${{ runner.os }}-test-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          uv-${{ runner.os }}-test-${{ hashFiles('requirements.txt') }}
          uv-${{ runner.os }}-test
          uv-${{ runner.os }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Clean installation
      run: |
        pip freeze --exclude-editable | xargs pip uninstall -y || pip freeze
    - name: Set up uv
      run: |
        pip install uv
        uv venv --python 3.9
    - name: Install test dependencies
      run: uv pip install -r requirements.txt --no-deps
    - name: Run tests
      run: >
        uv run --no-sync pytest
        --ignore=tests/test_examples.py
        -W "error::vanguard.utils.UnseededRandomWarning"
    - name: Minimize UV cache
      run: uv cache prune --ci
      if: always()
