name: Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install test dependencies
      run: pip install -e .
    - name: Test with pytest
      run: pytest --ignore=tests/test_examples.py
