name: Tests from requirements file

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        # TODO: Re-enable when going public
        # https://github.com/gchq/Vanguard/issues/257
        # cache: pip
        # cache-dependency-path: requirements.txt
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install test dependencies
      run: pip install -r requirements.txt --no-deps
    - name: Test with pytest
      run: pytest --ignore=tests/test_examples.py
